extends Node

const VIEWPORT_PADDING = 50

const EYE_RADIUS = 6
const PUPILLARY_DISTANCE = 15

const MAX_MOUSE_DISTANCE = 10
const MAX_POINT_DISTANCE = 30

const HEAD_TIP_POINT_INDEX = 0
const HEAD_CENTRE_POINT_INDEX = 1
const HEAD_BASE_POINT_INDEX = 2

const TAIL_BASE_POINT_INDEX = 0
const TAIL_TIP_POINT_INDEX = 1
